export const xyTheme = {
  bg: "#100030",
  bg2: "#200050",
  violet: "#7C3AED",
  violet2: "#8B5CF6",
  violet3: "#A855F7",
  indigo: "#7830C0",
  card: "#1A0A3A",
  border: "rgba(124,58,237,0.22)",
  gradient: "linear-gradient(135deg,#100030 0%,#200050 35%,#2D0A5E 55%,#7C3AED 100%)",
  btn: "linear-gradient(135deg,#7C3AED 0%,#8B5CF6 45%,#A855F7 100%)",
};

export const MENU = [
  { id: "dash", label: "Dashboard", icon: "📊", path: "/" },
  { id: "orders", label: "Pesanan", icon: "🧾", path: "/orders" },
  { id: "users", label: "Pengguna", icon: "👥", path: "/users" },
  { id: "plans", label: "Paket PC", icon: "🖥️", path: "/plans" },
  { id: "produk", label: "Produk Akun", icon: "🎮", path: "/produk" },
  { id: "banners", label: "Banner", icon: "🖼️", path: "/banners" },
  { id: "promosi", label: "Promosi", icon: "🎁", path: "/promosi" },
  { id: "voucher", label: "Voucher", icon: "🎟️", path: "/voucher" },
  { id: "topup", label: "TopUp", icon: "💳", path: "/topup" },
  { id: "unit", label: "Unit PC", icon: "⚡", path: "/unit" },
  { id: "live", label: "Live Monitor", icon: "📡", path: "/live", badge: "BARU" },
  { id: "security", label: "Security", icon: "🛡️", path: "/security" },
  { id: "keuangan", label: "Keuangan", icon: "💰", path: "/keuangan", badge: "BARU" },
  { id: "cs", label: "CS Realtime", icon: "💬", path: "/cs" },
  { id: "forum", label: "Forum", icon: "🗣️", path: "/forum" },
  { id: "ulasan", label: "Ulasan", icon: "⭐", path: "/ulasan" },
  { id: "statistik", label: "Statistik", icon: "📈", path: "/statistik" },
  { id: "analitik", label: "Analitik", icon: "📉", path: "/analitik" },
  { id: "rilis", label: "Rilis App", icon: "🚀", path: "/rilis", badge: "BARU" },
  { id: "push", label: "Push Notif", icon: "🔔", path: "/push", badge: "BARU" },
  { id: "media", label: "Media", icon: "📦", path: "/media" },
  { id: "audit", label: "Audit Log", icon: "📝", path: "/audit" },
  { id: "sistem", label: "Sistem", icon: "⚙️", path: "/sistem" },
  { id: "peran", label: "Peran Admin", icon: "👮", path: "/peran" },
] as const;
